modLoader="javafml" 
loaderVersion="[38,)" 
license="LGPL-3.0-or-later"

[[mods]] 
modId="uiinputundo" 
version="${file.jarVersion}" 
displayName="UI Input Undo" 
logoFile="uiinputundo.png" 
credits="" 
authors="TheCSDev" 
description='A client-side Minecraft mod that allows you to undo and redo text in UI input fields.'

[[dependencies.uiinputundo]]
    modId="forge" 
    mandatory=true 
    versionRange="[41,)" 
    ordering="NONE"
    side="CLIENT"

[[dependencies.uiinputundo]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.19,)"
    ordering="NONE"
    side="CLIENT"
